# Global information
source-id: "archway-1"
config-version: 1
properties:
    title: "Archway"
    hex: "#e45121"
    logo: "ar://hKb8dVx4E1NCUJ_BlhNOcyfQEta5r38SBXqsfPnAsWE"

networks:
    # Mainnet pools
    kyve-1:
        pools:
            - id: 2
              runtime: "kyvejs/tendermint"
            - id: 4
              runtime: "kyvejs/tendermint-ssync"
        integrations:
            ksync:
                binary-name: "archwayd"
                block-sync-pool: 2
                docs-url: "https://docs.archway.io/"
                state-sync-pool: 4

    # Testnet pools
    kaon-1:
        pools:
            - id: 2
              runtime: "kyvejs/tendermint"
            - id: 4
              runtime: "kyvejs/tendermint-ssync"
        integrations:
            ksync:
                binary-name: "archwayd"
                block-sync-pool: 2
                docs-url: "https://docs.archway.io/"
                state-sync-pool: 4