# Global information
source:
    title: "Archway"
    chain_id: "archway-1"
    hex: "#e45121"

# Mainnet pools
kyve-1:
    block_pool_id: 2
    state_pool_id: 4

# Testnet pools
kaon-1:
    block_pool_id: 2
    state_pool_id: 4
