# Global information
source_id: "dydx-mainnet-1"
config-version: 1
properties:
    title: "dYdX"
    hex: "#12121d"
    logo: "ar://34RVRPI9Ume67ZdNhqwQ42GkZa0NoulBXNiJFJQZ6uc"

networks:
    # Testnet pools
    kaon-1:
        pools:
            - id: 8
              runtime: "kyvejs/tendermint"
            - id: 9
              runtime: "kyvejs/tendermint-ssync"
        integrations:
            ksync:
                binary_name: "dydxprotocold"
                block_sync_pool: 8
                docs_url: "https://docs.dydx.exchange/"
                state_sync_pool: 9