# Global information

source-id: "osmosis-1"
config-version: 1
properties:
  title: "Osmosis"
  hex: "#8d07c7"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 1

  # Testnet pools
  kaon-1:
    pools:
      - id: 1
      - id: 5
