# Global information
source_id: "cosmoshub-4"
config-version: 1
properties:
  title: "Cosmos Hub"
  hex: "#6f3048"
  logo: "ar://TCHDYB2xfk4VcWqyxApoWiFgr354gNSMdIliv2KnkRo"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 0
        runtime: "kyvejs/tendermint-bsync"
    integrations:
      ksync:
        binary_name: "gaiad"
        block_sync_pool: 0
        docs_url: "https://docs.cosmos.network/"

  # Testnet pools
  kaon-1:
    pools:
      - id: 0
        runtime: "kyvejs/tendermint-bsync"
    integrations:
      ksync:
        binary_name: "gaiad"
        block_sync_pool: 0
        docs_url: "https://docs.cosmos.network/"