# Global information
source_id: "cronosmainnet_25-1"
config-version: 1
properties:
  hex: "#191b34"
  logo: "ar://BbNmwRFv11y68Jiele3wxZNYQTqRVn_ZK6BwJ5S2MCE"
  title: "Cronos"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 5
        runtime: "kyvejs/tendermint"
      - id: 6
        runtime: "kyvejs/tendermint-bsync"
    integrations:
      binary: "cronosd"
      block_sync_pool: 5
      docs: "https://docs.cronos.org/"
      state_sync_pool: 6

  # Testnet pools
  kaon-1:
    pools:
      - id: 6
        runtime: "kyvejs/tendermint"
      - id: 7
        runtime: "kyvejs/tendermint-bsync"
    integrations:
      binary: "cronosd"
      block_sync_pool: 6
      docs: "https://docs.cronos.org/"
      state_sync_pool: 7

