# Global information
source:
  title: "Cronos"
  chain_id: "cronosmainnet_25-1"
  hex: "#191b34"

# Mainnet pools
kyve-1:
  block_pool_id: 5
  state_pool_id: 6

# Testnet pools
kaon-1:
  block_pool_id: 6
  state_pool_id: 7
