name: Merge Source configs and write Source-Registry

on:
  push:
    paths:
      - '**.yml'

jobs:
  merge_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install required Python packages
        run: pip install -r .github/requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Merge Source configs and write Source-Registry
        run: python .github/validate_registry.py
        working-directory: ${{ github.workspace }}